version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "Diana-V2"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "Diana-V2"
