[versions]
loom = "1.17.20"
ksp = "2.3.11"
elementa = "762"
universalcraft = "517"

[plugins]
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
ksp-symbol-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

elementa = { group = "gg.essential", name = "elementa", version.ref = "elementa" }

universalcraft261 = { group = "gg.essential", name = "universalcraft-26.1-fabric", version.ref = "universalcraft" }
universalcraft262 = { group = "gg.essential", name = "universalcraft-26.2-fabric", version.ref = "universalcraft" }
