[versions]
loom = "1.17.20"
ksp = "2.3.11"

[plugins]
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
ksp-symbol-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
