name: build
on: [pull_request, push]

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-26.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'
      - name: build
        run: ./gradlew build --scan
      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: build/versions/
